/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.opensimkit;

import org.opensimkit.utilities.SerialPorts;

/**
 *
 * @author ahmedmaawy
 */
public class ConnectedPanel extends javax.swing.JPanel {

    /**
     * Creates new form ConnectedPanel
     */
    public ConnectedPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelConnectedTop = new javax.swing.JPanel();
        jLabelNowEditing = new javax.swing.JLabel();
        jLabelLiveEditing = new javax.swing.JLabel();
        jPanelConnectedBottom = new javax.swing.JPanel();
        jPanelLiveEdit = new javax.swing.JPanel();
        jPanelLiveEditHelp = new javax.swing.JPanel();
        jLabelAutoSave = new javax.swing.JLabel();
        jLabelAutoSaveSaving = new javax.swing.JLabel();
        jLabelSaveIcon = new javax.swing.JLabel();
        jPanelContentHelp = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanelConnectedTop.setBackground(new java.awt.Color(255, 255, 255));

        jLabelNowEditing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensimkit/resources/LiveSIMEditing.png"))); // NOI18N

        jLabelLiveEditing.setFont(new java.awt.Font("Lucida Grande", 1, 34)); // NOI18N
        jLabelLiveEditing.setText("You are live editing this SIM");

        org.jdesktop.layout.GroupLayout jPanelConnectedTopLayout = new org.jdesktop.layout.GroupLayout(jPanelConnectedTop);
        jPanelConnectedTop.setLayout(jPanelConnectedTopLayout);
        jPanelConnectedTopLayout.setHorizontalGroup(
            jPanelConnectedTopLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelConnectedTopLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabelNowEditing, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 61, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabelLiveEditing)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelConnectedTopLayout.setVerticalGroup(
            jPanelConnectedTopLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelConnectedTopLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelConnectedTopLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabelNowEditing, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .add(jPanelConnectedTopLayout.createSequentialGroup()
                        .add(15, 15, 15)
                        .add(jLabelLiveEditing)
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanelConnectedBottom.setBackground(new java.awt.Color(255, 255, 255));

        jPanelLiveEdit.setBackground(new java.awt.Color(255, 255, 255));

        org.jdesktop.layout.GroupLayout jPanelLiveEditLayout = new org.jdesktop.layout.GroupLayout(jPanelLiveEdit);
        jPanelLiveEdit.setLayout(jPanelLiveEditLayout);
        jPanelLiveEditLayout.setHorizontalGroup(
            jPanelLiveEditLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 277, Short.MAX_VALUE)
        );
        jPanelLiveEditLayout.setVerticalGroup(
            jPanelLiveEditLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 302, Short.MAX_VALUE)
        );

        jPanelLiveEditHelp.setBackground(new java.awt.Color(255, 255, 255));

        jLabelAutoSave.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabelAutoSave.setText("<html><div style=\"width:100%\">Changes are automatically saved as you type</div></html>");

        jLabelAutoSaveSaving.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabelAutoSaveSaving.setText("Saving now");

        jLabelSaveIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensimkit/resources/NowSaving.png"))); // NOI18N

        jPanelContentHelp.setBackground(new java.awt.Color(0, 65, 108));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<html><div style=\"width:100%\">For help and support from the SIMKit Community...</div></html>");

        org.jdesktop.layout.GroupLayout jPanelContentHelpLayout = new org.jdesktop.layout.GroupLayout(jPanelContentHelp);
        jPanelContentHelp.setLayout(jPanelContentHelpLayout);
        jPanelContentHelpLayout.setHorizontalGroup(
            jPanelContentHelpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelContentHelpLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 311, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(29, 29, 29))
        );
        jPanelContentHelpLayout.setVerticalGroup(
            jPanelContentHelpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelContentHelpLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout jPanelLiveEditHelpLayout = new org.jdesktop.layout.GroupLayout(jPanelLiveEditHelp);
        jPanelLiveEditHelp.setLayout(jPanelLiveEditHelpLayout);
        jPanelLiveEditHelpLayout.setHorizontalGroup(
            jPanelLiveEditHelpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelLiveEditHelpLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelLiveEditHelpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabelAutoSave, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanelLiveEditHelpLayout.createSequentialGroup()
                        .add(jLabelAutoSaveSaving)
                        .add(18, 18, 18)
                        .add(jLabelSaveIcon)))
                .addContainerGap(13, Short.MAX_VALUE))
            .add(jPanelLiveEditHelpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanelLiveEditHelpLayout.createSequentialGroup()
                    .addContainerGap()
                    .add(jPanelContentHelp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 326, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(12, Short.MAX_VALUE)))
        );
        jPanelLiveEditHelpLayout.setVerticalGroup(
            jPanelLiveEditHelpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelLiveEditHelpLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabelAutoSave, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelLiveEditHelpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabelSaveIcon, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabelAutoSaveSaving, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(236, Short.MAX_VALUE))
            .add(jPanelLiveEditHelpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelLiveEditHelpLayout.createSequentialGroup()
                    .addContainerGap(91, Short.MAX_VALUE)
                    .add(jPanelContentHelp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        org.jdesktop.layout.GroupLayout jPanelConnectedBottomLayout = new org.jdesktop.layout.GroupLayout(jPanelConnectedBottom);
        jPanelConnectedBottom.setLayout(jPanelConnectedBottomLayout);
        jPanelConnectedBottomLayout.setHorizontalGroup(
            jPanelConnectedBottomLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelConnectedBottomLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelLiveEdit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanelLiveEditHelp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelConnectedBottomLayout.setVerticalGroup(
            jPanelConnectedBottomLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelConnectedBottomLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelConnectedBottomLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelLiveEdit, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanelLiveEditHelp, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanelConnectedBottom, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanelConnectedTop, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelConnectedTop, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelConnectedBottom, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAutoSave;
    private javax.swing.JLabel jLabelAutoSaveSaving;
    private javax.swing.JLabel jLabelLiveEditing;
    private javax.swing.JLabel jLabelNowEditing;
    private javax.swing.JLabel jLabelSaveIcon;
    private javax.swing.JPanel jPanelConnectedBottom;
    private javax.swing.JPanel jPanelConnectedTop;
    private javax.swing.JPanel jPanelContentHelp;
    private javax.swing.JPanel jPanelLiveEdit;
    private javax.swing.JPanel jPanelLiveEditHelp;
    // End of variables declaration//GEN-END:variables
}
