/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.opensimkit;

import org.opensimkit.utilities.SerialPorts;

/**
 *
 * @author ahmedmaawy
 */
public class ConnectedPanel extends javax.swing.JPanel {

    /**
     * Creates new form ConnectedPanel
     */
    public ConnectedPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelConnectedTop = new javax.swing.JPanel();
        jLabelLiveEditing = new javax.swing.JLabel();
        jPanelConnectedBottom = new javax.swing.JPanel();
        jPanelLiveEdit = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanelLiveEditHelp = new javax.swing.JPanel();
        jLabelAutoSave = new javax.swing.JLabel();
        jButtonSave = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelAutoSave1 = new javax.swing.JLabel();
        jButtonEject = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanelConnectedTop.setBackground(new java.awt.Color(255, 255, 255));

        jLabelLiveEditing.setFont(new java.awt.Font("Lucida Grande", 1, 28)); // NOI18N
        jLabelLiveEditing.setText("You are currently editing a SIM card");

        org.jdesktop.layout.GroupLayout jPanelConnectedTopLayout = new org.jdesktop.layout.GroupLayout(jPanelConnectedTop);
        jPanelConnectedTop.setLayout(jPanelConnectedTopLayout);
        jPanelConnectedTopLayout.setHorizontalGroup(
            jPanelConnectedTopLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelConnectedTopLayout.createSequentialGroup()
                .add(27, 27, 27)
                .add(jLabelLiveEditing)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelConnectedTopLayout.setVerticalGroup(
            jPanelConnectedTopLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelConnectedTopLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .add(jLabelLiveEditing)
                .add(26, 26, 26))
        );

        jPanelConnectedBottom.setBackground(new java.awt.Color(255, 255, 255));

        jPanelLiveEdit.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        org.jdesktop.layout.GroupLayout jPanelLiveEditLayout = new org.jdesktop.layout.GroupLayout(jPanelLiveEdit);
        jPanelLiveEdit.setLayout(jPanelLiveEditLayout);
        jPanelLiveEditLayout.setHorizontalGroup(
            jPanelLiveEditLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelLiveEditLayout.createSequentialGroup()
                .add(0, 265, Short.MAX_VALUE)
                .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        jPanelLiveEditLayout.setVerticalGroup(
            jPanelLiveEditLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelLiveEditLayout.createSequentialGroup()
                .addContainerGap()
                .add(jSeparator2)
                .addContainerGap())
        );

        jPanelLiveEditHelp.setBackground(new java.awt.Color(255, 255, 255));

        jLabelAutoSave.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabelAutoSave.setText("<html> <div style=\"width:100%\"> <p>Edit the text in any of the boxes in the list on the left</p> <br/> <p>When you have finished editing click on the save button below to store those messages on card.</p> </div> </html>");

        jButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensimkit/resources/SaveButton.png"))); // NOI18N
        jButtonSave.setBorder(null);

        jLabelAutoSave1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabelAutoSave1.setText("<html> <div style=\"width:100%\"> <p>Edit the text in any of the boxes in the list on the left</p> <br/> <p>When you have finished editing click on the save button below to store those messages on card.</p> </div> </html>");

        jButtonEject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensimkit/resources/EjectButton.png"))); // NOI18N
        jButtonEject.setBorder(null);

        org.jdesktop.layout.GroupLayout jPanelLiveEditHelpLayout = new org.jdesktop.layout.GroupLayout(jPanelLiveEditHelp);
        jPanelLiveEditHelp.setLayout(jPanelLiveEditHelpLayout);
        jPanelLiveEditHelpLayout.setHorizontalGroup(
            jPanelLiveEditHelpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelLiveEditHelpLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelLiveEditHelpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelLiveEditHelpLayout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(jPanelLiveEditHelpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabelAutoSave, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 320, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelLiveEditHelpLayout.createSequentialGroup()
                                .add(jButtonSave)
                                .addContainerGap())))
                    .add(jPanelLiveEditHelpLayout.createSequentialGroup()
                        .add(jSeparator1)
                        .addContainerGap())
                    .add(jPanelLiveEditHelpLayout.createSequentialGroup()
                        .add(jLabelAutoSave1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 320, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE))))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelLiveEditHelpLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jButtonEject)
                .addContainerGap())
        );
        jPanelLiveEditHelpLayout.setVerticalGroup(
            jPanelLiveEditHelpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelLiveEditHelpLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabelAutoSave, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButtonSave)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabelAutoSave1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButtonEject))
        );

        org.jdesktop.layout.GroupLayout jPanelConnectedBottomLayout = new org.jdesktop.layout.GroupLayout(jPanelConnectedBottom);
        jPanelConnectedBottom.setLayout(jPanelConnectedBottomLayout);
        jPanelConnectedBottomLayout.setHorizontalGroup(
            jPanelConnectedBottomLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelConnectedBottomLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelLiveEdit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanelLiveEditHelp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelConnectedBottomLayout.setVerticalGroup(
            jPanelConnectedBottomLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelConnectedBottomLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelConnectedBottomLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelLiveEdit, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanelLiveEditHelp, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanelConnectedBottom, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanelConnectedTop, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelConnectedTop, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelConnectedBottom, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEject;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabelAutoSave;
    private javax.swing.JLabel jLabelAutoSave1;
    private javax.swing.JLabel jLabelLiveEditing;
    private javax.swing.JPanel jPanelConnectedBottom;
    private javax.swing.JPanel jPanelConnectedTop;
    private javax.swing.JPanel jPanelLiveEdit;
    private javax.swing.JPanel jPanelLiveEditHelp;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
