/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.opensimkit;

import javax.swing.JPanel;

/**
 *
 * @author ahmedmaawy
 */
public class DisconnectedPanel extends javax.swing.JPanel {

    /**
     * Creates new form DisconnectedPanel
     */
    public DisconnectedPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBottomRightHeading = new javax.swing.JPanel();
        jLabelConnectionStatus = new javax.swing.JLabel();
        jLabelConnectionStatusText = new javax.swing.JLabel();
        jPanelBottomRightContent = new javax.swing.JPanel();
        jPanelContentInfo = new javax.swing.JPanel();
        jLabelConnectivityIssueText = new javax.swing.JLabel();
        jPanelContentHelp = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanelBottomRightHeading.setBackground(new java.awt.Color(255, 255, 255));

        jLabelConnectionStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensimkit/resources/NoSIMCard.png"))); // NOI18N

        jLabelConnectionStatusText.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabelConnectionStatusText.setText("No SIM Card Connected");

        org.jdesktop.layout.GroupLayout jPanelBottomRightHeadingLayout = new org.jdesktop.layout.GroupLayout(jPanelBottomRightHeading);
        jPanelBottomRightHeading.setLayout(jPanelBottomRightHeadingLayout);
        jPanelBottomRightHeadingLayout.setHorizontalGroup(
            jPanelBottomRightHeadingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelBottomRightHeadingLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabelConnectionStatus)
                .add(18, 18, 18)
                .add(jLabelConnectionStatusText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelBottomRightHeadingLayout.setVerticalGroup(
            jPanelBottomRightHeadingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelBottomRightHeadingLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelBottomRightHeadingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabelConnectionStatus, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabelConnectionStatusText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelBottomRightContent.setBackground(new java.awt.Color(255, 255, 255));

        jPanelContentInfo.setBackground(new java.awt.Color(255, 255, 255));

        jLabelConnectivityIssueText.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelConnectivityIssueText.setForeground(new java.awt.Color(255, 255, 255));
        jLabelConnectivityIssueText.setText("Info on the connectivity issue");

        org.jdesktop.layout.GroupLayout jPanelContentInfoLayout = new org.jdesktop.layout.GroupLayout(jPanelContentInfo);
        jPanelContentInfo.setLayout(jPanelContentInfoLayout);
        jPanelContentInfoLayout.setHorizontalGroup(
            jPanelContentInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelContentInfoLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabelConnectivityIssueText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelContentInfoLayout.setVerticalGroup(
            jPanelContentInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelContentInfoLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabelConnectivityIssueText)
                .addContainerGap(358, Short.MAX_VALUE))
        );

        jPanelContentHelp.setBackground(new java.awt.Color(0, 65, 108));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<html><div style=\"width:100%\">For help and support from the SIMKit Community...</div></html>");

        org.jdesktop.layout.GroupLayout jPanelContentHelpLayout = new org.jdesktop.layout.GroupLayout(jPanelContentHelp);
        jPanelContentHelp.setLayout(jPanelContentHelpLayout);
        jPanelContentHelpLayout.setHorizontalGroup(
            jPanelContentHelpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelContentHelpLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelContentHelpLayout.setVerticalGroup(
            jPanelContentHelpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelContentHelpLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(358, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPanelBottomRightContentLayout = new org.jdesktop.layout.GroupLayout(jPanelBottomRightContent);
        jPanelBottomRightContent.setLayout(jPanelBottomRightContentLayout);
        jPanelBottomRightContentLayout.setHorizontalGroup(
            jPanelBottomRightContentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelBottomRightContentLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelContentInfo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanelContentHelp, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelBottomRightContentLayout.setVerticalGroup(
            jPanelBottomRightContentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelBottomRightContentLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelBottomRightContentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelContentInfo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanelContentHelp, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelBottomRightHeading, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanelBottomRightContent, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelBottomRightHeading, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelBottomRightContent, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelConnectionStatus;
    private javax.swing.JLabel jLabelConnectionStatusText;
    private javax.swing.JLabel jLabelConnectivityIssueText;
    private javax.swing.JPanel jPanelBottomRightContent;
    private javax.swing.JPanel jPanelBottomRightHeading;
    private javax.swing.JPanel jPanelContentHelp;
    private javax.swing.JPanel jPanelContentInfo;
    // End of variables declaration//GEN-END:variables
}
