/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.opensimkit;

import org.opensimkit.utilities.DeviceConnection;
import org.opensimkit.utilities.SerialPorts;

/**
 *
 * @author ahmedmaawy
 */
public class DisconnectedPanel extends javax.swing.JPanel {

    /**
     * Creates new form DisconnectedPanel
     */
    public DisconnectedPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanelBottomRightHeading = new javax.swing.JPanel();
        jLabelConnectionStatusText = new javax.swing.JLabel();
        jLabelConnectInfo = new javax.swing.JLabel();
        jButtonAutoConnect = new javax.swing.JButton();
        jLabelCouldNotDetect = new javax.swing.JLabel();
        jLabelPossibleConnectionErrors = new javax.swing.JLabel();
        jPanelBottomRightContent = new javax.swing.JPanel();
        jPanelContentInfo = new javax.swing.JPanel();
        jLabelCouldNotFindIcom = new javax.swing.JLabel();
        jPanelContentHelp = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelHelpItem1 = new javax.swing.JLabel();
        jLabelHelpIcon1 = new javax.swing.JLabel();
        jLabelHelpItem2 = new javax.swing.JLabel();
        jLabelHelpIcon2 = new javax.swing.JLabel();
        jLabelHelpItem3 = new javax.swing.JLabel();
        jLabelHelpIcon3 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setBackground(new java.awt.Color(255, 255, 255));

        jPanelBottomRightHeading.setBackground(new java.awt.Color(255, 255, 255));

        jLabelConnectionStatusText.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabelConnectionStatusText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelConnectionStatusText.setText("There is no SIM card connected that SIMKit can work with");

        jLabelConnectInfo.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabelConnectInfo.setText("<html><div style=\"width:100%\"><p>If you want to rescan your system for SIM card, click the button here</p></div></html>");

        jButtonAutoConnect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensimkit/resources/CheckAgainButton.png"))); // NOI18N
        jButtonAutoConnect.setBorder(null);
        jButtonAutoConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAutoConnectActionPerformed(evt);
            }
        });

        jLabelCouldNotDetect.setText("SIMKit could not detect any connected cards that can be used at the moment");

        jLabelPossibleConnectionErrors.setText("<html><div style=\"width:100%\"><p>Have a loomk at the possible connection errors below. If they dont help you solve the problem, look at the help links on the right.</p></div></html>");

        org.jdesktop.layout.GroupLayout jPanelBottomRightHeadingLayout = new org.jdesktop.layout.GroupLayout(jPanelBottomRightHeading);
        jPanelBottomRightHeading.setLayout(jPanelBottomRightHeadingLayout);
        jPanelBottomRightHeadingLayout.setHorizontalGroup(
            jPanelBottomRightHeadingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLabelConnectionStatusText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
            .add(jPanelBottomRightHeadingLayout.createSequentialGroup()
                .add(jPanelBottomRightHeadingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelBottomRightHeadingLayout.createSequentialGroup()
                        .add(84, 84, 84)
                        .add(jLabelConnectInfo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 250, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonAutoConnect)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelBottomRightHeadingLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabelPossibleConnectionErrors, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .add(jPanelBottomRightHeadingLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabelCouldNotDetect, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelBottomRightHeadingLayout.setVerticalGroup(
            jPanelBottomRightHeadingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelBottomRightHeadingLayout.createSequentialGroup()
                .add(jLabelConnectionStatusText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanelBottomRightHeadingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jButtonAutoConnect)
                    .add(jLabelConnectInfo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabelCouldNotDetect)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabelPossibleConnectionErrors, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelBottomRightContent.setBackground(new java.awt.Color(255, 255, 255));

        jPanelContentInfo.setBackground(new java.awt.Color(255, 255, 255));

        jLabelCouldNotFindIcom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensimkit/resources/OpenSIMKitConnectionError.png"))); // NOI18N

        org.jdesktop.layout.GroupLayout jPanelContentInfoLayout = new org.jdesktop.layout.GroupLayout(jPanelContentInfo);
        jPanelContentInfo.setLayout(jPanelContentInfoLayout);
        jPanelContentInfoLayout.setHorizontalGroup(
            jPanelContentInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelContentInfoLayout.createSequentialGroup()
                .add(16, 16, 16)
                .add(jLabelCouldNotFindIcom)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanelContentInfoLayout.setVerticalGroup(
            jPanelContentInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelContentInfoLayout.createSequentialGroup()
                .add(105, 105, 105)
                .add(jLabelCouldNotFindIcom)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jPanelContentHelp.setBackground(new java.awt.Color(255, 204, 102));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("<html><div style=\"width:100%\">Need some help?</div></html>");

        jLabelHelpItem1.setText("<html><div style=\"width:100%\"><p>For step by step instructions on using OpenSIMKit, click here</p></div></html>");

        jLabelHelpIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensimkit/resources/HelpIcon.png"))); // NOI18N

        jLabelHelpItem2.setText("<html><div style=\"width:100%\"><p>For a list of supported devices and ways to connect them, click here</p></div></html>");

        jLabelHelpIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensimkit/resources/HelpIcon.png"))); // NOI18N

        jLabelHelpItem3.setText("<html><div style=\"width:100%\"><p>To get involved and contribute to the development of OpenSIMKit, click here</p></div></html>");

        jLabelHelpIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensimkit/resources/HelpIcon.png"))); // NOI18N

        org.jdesktop.layout.GroupLayout jPanelContentHelpLayout = new org.jdesktop.layout.GroupLayout(jPanelContentHelp);
        jPanelContentHelp.setLayout(jPanelContentHelpLayout);
        jPanelContentHelpLayout.setHorizontalGroup(
            jPanelContentHelpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelContentHelpLayout.createSequentialGroup()
                .add(96, 96, 96)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelContentHelpLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanelContentHelpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelContentHelpLayout.createSequentialGroup()
                        .add(jLabelHelpIcon1)
                        .add(18, 18, 18)
                        .add(jLabelHelpItem1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 216, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelContentHelpLayout.createSequentialGroup()
                        .add(jLabelHelpIcon2)
                        .add(18, 18, 18)
                        .add(jLabelHelpItem2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 216, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelContentHelpLayout.createSequentialGroup()
                        .add(jLabelHelpIcon3)
                        .add(18, 18, 18)
                        .add(jLabelHelpItem3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 216, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelContentHelpLayout.setVerticalGroup(
            jPanelContentHelpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelContentHelpLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanelContentHelpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabelHelpIcon1)
                    .add(jLabelHelpItem1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanelContentHelpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabelHelpIcon2)
                    .add(jLabelHelpItem2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelContentHelpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabelHelpIcon3)
                    .add(jLabelHelpItem3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(142, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPanelBottomRightContentLayout = new org.jdesktop.layout.GroupLayout(jPanelBottomRightContent);
        jPanelBottomRightContent.setLayout(jPanelBottomRightContentLayout);
        jPanelBottomRightContentLayout.setHorizontalGroup(
            jPanelBottomRightContentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelBottomRightContentLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelContentInfo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanelContentHelp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        jPanelBottomRightContentLayout.setVerticalGroup(
            jPanelBottomRightContentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelBottomRightContentLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanelBottomRightContentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanelContentInfo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanelContentHelp, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelBottomRightHeading, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelBottomRightContent, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelBottomRightHeading, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelBottomRightContent, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAutoConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAutoConnectActionPerformed
        
        // Connect to the device
        
        DeviceConnection deviceConnection = new DeviceConnection();
        
        if(!OpenSIMKit.deviceConnection.connectViaDrivers())
            OpenSIMKit.deviceConnection.connectViaGeneric();
    }//GEN-LAST:event_jButtonAutoConnectActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAutoConnect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelConnectInfo;
    private javax.swing.JLabel jLabelConnectionStatusText;
    private javax.swing.JLabel jLabelCouldNotDetect;
    private javax.swing.JLabel jLabelCouldNotFindIcom;
    private javax.swing.JLabel jLabelHelpIcon1;
    private javax.swing.JLabel jLabelHelpIcon2;
    private javax.swing.JLabel jLabelHelpIcon3;
    private javax.swing.JLabel jLabelHelpItem1;
    private javax.swing.JLabel jLabelHelpItem2;
    private javax.swing.JLabel jLabelHelpItem3;
    private javax.swing.JLabel jLabelPossibleConnectionErrors;
    private javax.swing.JPanel jPanelBottomRightContent;
    private javax.swing.JPanel jPanelBottomRightHeading;
    private javax.swing.JPanel jPanelContentHelp;
    private javax.swing.JPanel jPanelContentInfo;
    // End of variables declaration//GEN-END:variables
}
