/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.opensimkit;

import javax.swing.JPanel;

/**
 *
 * @author ahmedmaawy
 */
public class DisconnectedPanel extends javax.swing.JPanel {

    /**
     * Creates new form DisconnectedPanel
     */
    public DisconnectedPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanelBottomRightHeading = new javax.swing.JPanel();
        jLabelConnectionStatusText = new javax.swing.JLabel();
        jLabelConnectInfo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelCouldNotDetect = new javax.swing.JLabel();
        jLabelPossibleConnectionErrors = new javax.swing.JLabel();
        jPanelBottomRightContent = new javax.swing.JPanel();
        jPanelContentInfo = new javax.swing.JPanel();
        jLabelCouldNotFindIcom = new javax.swing.JLabel();
        jPanelContentHelp = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setBackground(new java.awt.Color(255, 255, 255));

        jPanelBottomRightHeading.setBackground(new java.awt.Color(255, 255, 255));

        jLabelConnectionStatusText.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabelConnectionStatusText.setText("There is no SIM card connected that SIMKit can work with");

        jLabelConnectInfo.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabelConnectInfo.setText("<html><div style=\"width:100%\"><p>If you want to rescan your system for SIM card, click the button here</p></div></html>");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensimkit/resources/CheckAgainButton.png"))); // NOI18N
        jButton1.setBorder(null);

        jLabelCouldNotDetect.setText("SIMKit could not detect any connected cards that can be used at the moment");

        jLabelPossibleConnectionErrors.setText("<html><div style=\"width:100%\"><p>Have a loomk at the possible connection errors below. If they dont help you solve the problem, look at the help links on the right.</p></div></html>");

        org.jdesktop.layout.GroupLayout jPanelBottomRightHeadingLayout = new org.jdesktop.layout.GroupLayout(jPanelBottomRightHeading);
        jPanelBottomRightHeading.setLayout(jPanelBottomRightHeadingLayout);
        jPanelBottomRightHeadingLayout.setHorizontalGroup(
            jPanelBottomRightHeadingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLabelConnectionStatusText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jPanelBottomRightHeadingLayout.createSequentialGroup()
                .add(jPanelBottomRightHeadingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelBottomRightHeadingLayout.createSequentialGroup()
                        .add(84, 84, 84)
                        .add(jLabelConnectInfo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 250, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton1)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelBottomRightHeadingLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabelPossibleConnectionErrors, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .add(jPanelBottomRightHeadingLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabelCouldNotDetect, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelBottomRightHeadingLayout.setVerticalGroup(
            jPanelBottomRightHeadingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelBottomRightHeadingLayout.createSequentialGroup()
                .add(jLabelConnectionStatusText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanelBottomRightHeadingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jButton1)
                    .add(jLabelConnectInfo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabelCouldNotDetect)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabelPossibleConnectionErrors, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelBottomRightContent.setBackground(new java.awt.Color(255, 255, 255));

        jPanelContentInfo.setBackground(new java.awt.Color(255, 255, 255));

        jLabelCouldNotFindIcom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensimkit/resources/OpenSIMKitConnectionError.png"))); // NOI18N

        org.jdesktop.layout.GroupLayout jPanelContentInfoLayout = new org.jdesktop.layout.GroupLayout(jPanelContentInfo);
        jPanelContentInfo.setLayout(jPanelContentInfoLayout);
        jPanelContentInfoLayout.setHorizontalGroup(
            jPanelContentInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelContentInfoLayout.createSequentialGroup()
                .add(16, 16, 16)
                .add(jLabelCouldNotFindIcom)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanelContentInfoLayout.setVerticalGroup(
            jPanelContentInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelContentInfoLayout.createSequentialGroup()
                .add(105, 105, 105)
                .add(jLabelCouldNotFindIcom)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jPanelContentHelp.setBackground(new java.awt.Color(255, 204, 102));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("<html><div style=\"width:100%\">Need some help?</div></html>");

        org.jdesktop.layout.GroupLayout jPanelContentHelpLayout = new org.jdesktop.layout.GroupLayout(jPanelContentHelp);
        jPanelContentHelp.setLayout(jPanelContentHelpLayout);
        jPanelContentHelpLayout.setHorizontalGroup(
            jPanelContentHelpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelContentHelpLayout.createSequentialGroup()
                .add(87, 87, 87)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanelContentHelpLayout.setVerticalGroup(
            jPanelContentHelpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelContentHelpLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(256, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPanelBottomRightContentLayout = new org.jdesktop.layout.GroupLayout(jPanelBottomRightContent);
        jPanelBottomRightContent.setLayout(jPanelBottomRightContentLayout);
        jPanelBottomRightContentLayout.setHorizontalGroup(
            jPanelBottomRightContentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelBottomRightContentLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelContentInfo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanelContentHelp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        jPanelBottomRightContentLayout.setVerticalGroup(
            jPanelBottomRightContentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelBottomRightContentLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanelBottomRightContentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanelContentInfo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanelContentHelp, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelBottomRightHeading, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelBottomRightContent, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelBottomRightHeading, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelBottomRightContent, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelConnectInfo;
    private javax.swing.JLabel jLabelConnectionStatusText;
    private javax.swing.JLabel jLabelCouldNotDetect;
    private javax.swing.JLabel jLabelCouldNotFindIcom;
    private javax.swing.JLabel jLabelPossibleConnectionErrors;
    private javax.swing.JPanel jPanelBottomRightContent;
    private javax.swing.JPanel jPanelBottomRightHeading;
    private javax.swing.JPanel jPanelContentHelp;
    private javax.swing.JPanel jPanelContentInfo;
    // End of variables declaration//GEN-END:variables
}
