/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.opensimkit;

/**
 *
 * @author ahmedmaawy
 */
public class MainFrame extends javax.swing.JFrame {
    
    /**
     * Creates new form MainJFrame
     */
    public MainFrame() {
        initComponents();
        connectedPanel.setVisible(false);
    }
    
    /**
     * Change the interface to a connected one
     */
    
    public void setConnectedInterface()
    {
        connectedPanel.setVisible(true);
        disconnectedPanel.setVisible(false);
    }
    
    /**
     * Change the interface to a disconnected one
     */
    
    public void setDisconnectedInterface()
    {
        connectedPanel.setVisible(false);
        disconnectedPanel.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonTwitter1 = new javax.swing.JButton();
        SIMKitLogo = new javax.swing.JLabel();
        jPanelBottomLeft = new javax.swing.JPanel();
        jLabelAboutOSK = new javax.swing.JLabel();
        jButtonFaceBook = new javax.swing.JButton();
        jButtonGitHub = new javax.swing.JButton();
        jButtonTwitter = new javax.swing.JButton();
        jButtonRSS = new javax.swing.JButton();
        jPanelBottomRight = new javax.swing.JPanel();
        disconnectedPanel = new org.opensimkit.DisconnectedPanel();
        connectedPanel = new org.opensimkit.ConnectedPanel();
        jLabelAbayimaLogo = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemConnect = new javax.swing.JMenuItem();
        jMenuItemSettings = new javax.swing.JMenuItem();
        jMenuItemExit = new javax.swing.JMenuItem();

        jButtonTwitter1.setBackground(new java.awt.Color(26, 26, 26));
        jButtonTwitter1.setForeground(new java.awt.Color(26, 26, 26));
        jButtonTwitter1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensimkit/resources/GitHub.png"))); // NOI18N
        jButtonTwitter1.setBorder(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        SIMKitLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensimkit/resources/SIMKitLogo.png"))); // NOI18N

        jPanelBottomLeft.setBackground(new java.awt.Color(255, 255, 255));

        jLabelAboutOSK.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelAboutOSK.setText("<html><div style=\"width:100%;\">SIMKIT is a free and open source software designed to turn the world's feature phones into low cost e-readers</div></html>");

        jButtonFaceBook.setBackground(new java.awt.Color(26, 26, 26));
        jButtonFaceBook.setForeground(new java.awt.Color(26, 26, 26));
        jButtonFaceBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensimkit/resources/Facebook.png"))); // NOI18N
        jButtonFaceBook.setBorder(null);

        jButtonGitHub.setBackground(new java.awt.Color(26, 26, 26));
        jButtonGitHub.setForeground(new java.awt.Color(26, 26, 26));
        jButtonGitHub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensimkit/resources/GitHub.png"))); // NOI18N
        jButtonGitHub.setBorder(null);

        jButtonTwitter.setBackground(new java.awt.Color(26, 26, 26));
        jButtonTwitter.setForeground(new java.awt.Color(26, 26, 26));
        jButtonTwitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensimkit/resources/Twitter.png"))); // NOI18N
        jButtonTwitter.setBorder(null);

        jButtonRSS.setBackground(new java.awt.Color(26, 26, 26));
        jButtonRSS.setForeground(new java.awt.Color(26, 26, 26));
        jButtonRSS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensimkit/resources/RSS.png"))); // NOI18N
        jButtonRSS.setBorder(null);

        org.jdesktop.layout.GroupLayout jPanelBottomLeftLayout = new org.jdesktop.layout.GroupLayout(jPanelBottomLeft);
        jPanelBottomLeft.setLayout(jPanelBottomLeftLayout);
        jPanelBottomLeftLayout.setHorizontalGroup(
            jPanelBottomLeftLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelBottomLeftLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelBottomLeftLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelBottomLeftLayout.createSequentialGroup()
                        .add(jLabelAboutOSK, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 231, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(jPanelBottomLeftLayout.createSequentialGroup()
                        .add(jButtonGitHub)
                        .add(18, 18, 18)
                        .add(jButtonFaceBook)
                        .add(18, 18, 18)
                        .add(jButtonTwitter)
                        .add(18, 18, 18)
                        .add(jButtonRSS)
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelBottomLeftLayout.setVerticalGroup(
            jPanelBottomLeftLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelBottomLeftLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabelAboutOSK, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 58, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanelBottomLeftLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jButtonFaceBook)
                    .add(jButtonGitHub)
                    .add(jButtonTwitter)
                    .add(jButtonRSS))
                .addContainerGap(407, Short.MAX_VALUE))
        );

        jPanelBottomRight.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBottomRight.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));

        org.jdesktop.layout.GroupLayout jPanelBottomRightLayout = new org.jdesktop.layout.GroupLayout(jPanelBottomRight);
        jPanelBottomRight.setLayout(jPanelBottomRightLayout);
        jPanelBottomRightLayout.setHorizontalGroup(
            jPanelBottomRightLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelBottomRightLayout.createSequentialGroup()
                .addContainerGap()
                .add(disconnectedPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 709, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(connectedPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBottomRightLayout.setVerticalGroup(
            jPanelBottomRightLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelBottomRightLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .add(jPanelBottomRightLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelBottomRightLayout.createSequentialGroup()
                        .add(disconnectedPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 512, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(25, 25, 25))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelBottomRightLayout.createSequentialGroup()
                        .add(connectedPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jLabelAbayimaLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensimkit/resources/AbayimaLogo.png"))); // NOI18N

        jMenuFile.setText("File");

        jMenuItemConnect.setText("Connect");
        jMenuItemConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConnectActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemConnect);

        jMenuItemSettings.setText("Settings");
        jMenuItemSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSettingsActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemSettings);

        jMenuItemExit.setText("Exit");
        jMenuFile.add(jMenuItemExit);

        jMenuBar.add(jMenuFile);

        setJMenuBar(jMenuBar);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jPanelBottomLeft, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanelBottomRight, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(SIMKitLogo)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jLabelAbayimaLogo)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, SIMKitLogo)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabelAbayimaLogo))
                .add(7, 7, 7)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelBottomRight, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanelBottomLeft, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSettingsActionPerformed
        // TODO add your handling code here:
        SettingsFrame settingsFrame = new SettingsFrame();
        settingsFrame.setVisible(true);
    }//GEN-LAST:event_jMenuItemSettingsActionPerformed

    private void jMenuItemConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConnectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemConnectActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SIMKitLogo;
    private org.opensimkit.ConnectedPanel connectedPanel;
    private org.opensimkit.DisconnectedPanel disconnectedPanel;
    private javax.swing.JButton jButtonFaceBook;
    private javax.swing.JButton jButtonGitHub;
    private javax.swing.JButton jButtonRSS;
    private javax.swing.JButton jButtonTwitter;
    private javax.swing.JButton jButtonTwitter1;
    private javax.swing.JLabel jLabelAbayimaLogo;
    private javax.swing.JLabel jLabelAboutOSK;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemConnect;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemSettings;
    private javax.swing.JPanel jPanelBottomLeft;
    private javax.swing.JPanel jPanelBottomRight;
    // End of variables declaration//GEN-END:variables
}
