/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.opensimkit;

import java.util.ArrayList;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import org.jdesktop.layout.GroupLayout;

/**
 *
 * @author ahmedmaawy
 */
public class MessagesPanel extends javax.swing.JPanel {

    /**
     * Creates new form MessagesPanel
     */
    
    private ArrayList<JScrollPane> jScrollPaneList = new ArrayList<JScrollPane>();
    private ArrayList<JTextArea> jTextAreaList = new ArrayList<JTextArea>();
    private int numItems;
    
    public MessagesPanel() {
        initComponents();
    }
    
    /**
     * Sets items to be displayed in the panel
     * 
     * @param items 
     */
    
    public void setItems(ArrayList<String> items) {
        
        numItems = items.size();
        
        jTextAreaList.clear();
        jScrollPaneList.clear();
        
        this.removeAll();
        
        for(int itemLoop = 0; itemLoop <= numItems; itemLoop ++) {
            JScrollPane jScrollPaneMessage = new javax.swing.JScrollPane();
            JTextArea jTextAreaMessage = new javax.swing.JTextArea();
            
            // We need the last one to be empty for a new message
            
            if(itemLoop < numItems)
                jTextAreaMessage.setText(items.get(itemLoop));
            
            jTextAreaMessage.setLineWrap(true);

            jTextAreaMessage.setColumns(20);
            jTextAreaMessage.setRows(5);
            jScrollPaneMessage.setViewportView(jTextAreaMessage);
            
            jTextAreaList.add(jTextAreaMessage);
            jScrollPaneList.add(jScrollPaneMessage);
        }
        
        // Create a layout
        
        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        
        // Add horizontal sequential group
        
        GroupLayout.ParallelGroup horizontalSequentialGroup = layout.createParallelGroup();
        
        for(int itemLoop = 0; itemLoop <= numItems; itemLoop ++) {
            horizontalSequentialGroup.add(jScrollPaneList.get(itemLoop), org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE);
        }
        
        layout.setHorizontalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(horizontalSequentialGroup));
        // Add vertical sequential group
        
        GroupLayout.SequentialGroup verticalSequentialGroup = layout.createSequentialGroup();
        
        for(int itemLoop = 0; itemLoop <= numItems; itemLoop ++) {
            verticalSequentialGroup.addContainerGap();
            verticalSequentialGroup.add(jScrollPaneList.get(itemLoop), org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE);
            verticalSequentialGroup.addContainerGap();
        }
        
        layout.setVerticalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(verticalSequentialGroup));
    }
    
    /**
     * Gets all generated text controls
     * 
     * @return 
     */

    public ArrayList<JTextArea> getjTextAreaList() {
        return jTextAreaList;
    }
    
    /**
     * Gets number of items
     * 
     * @return 
     */

    public int getNumItems() {
        return numItems;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 294, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 375, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
