/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.opensimkit;

import javax.swing.ImageIcon;

/**
 *
 * @author ahmedmaawy
 */
public class PermissionsPanel extends javax.swing.JPanel {

    private boolean usageYes = false;
    private boolean turnedOnYes = false;
    
    private ImageIcon yesNoNoIcon;
    private ImageIcon yesNoYesIcon;
    
    /**
     * Creates new form PermissionsPanel
     */
    public PermissionsPanel() {
        initComponents();
        
        yesNoNoIcon = new javax.swing.ImageIcon(getClass().getResource("/org/opensimkit/resources/YesNoNo.png"));
        yesNoYesIcon = new javax.swing.ImageIcon(getClass().getResource("/org/opensimkit/resources/YesNoYes.png"));
    }
    
    /**
     * The usage toggle status
     * 
     * @return 
     */

    public boolean isUsageYes() {
        return usageYes;
    }
    
    /**
     * The turned on toggle status
     * 
     * @return 
     */

    public boolean isTurnedOnYes() {
        return turnedOnYes;
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPermissionsTop = new javax.swing.JPanel();
        jLabelLiveEditing = new javax.swing.JLabel();
        jPanelPermissionsBottom = new javax.swing.JPanel();
        jLabelRecordInfo = new javax.swing.JLabel();
        jLabelCollectAnonymous = new javax.swing.JLabel();
        jLabelCollectUsage = new javax.swing.JLabel();
        jToggleButtonUsage = new javax.swing.JToggleButton();
        jToggleButtonTurnedOn = new javax.swing.JToggleButton();
        jButtonContinue = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanelPermissionsTop.setBackground(new java.awt.Color(255, 255, 255));

        jLabelLiveEditing.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabelLiveEditing.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLiveEditing.setText("Can we record your use of OpenSIMKit?");

        org.jdesktop.layout.GroupLayout jPanelPermissionsTopLayout = new org.jdesktop.layout.GroupLayout(jPanelPermissionsTop);
        jPanelPermissionsTop.setLayout(jPanelPermissionsTopLayout);
        jPanelPermissionsTopLayout.setHorizontalGroup(
            jPanelPermissionsTopLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelPermissionsTopLayout.createSequentialGroup()
                .add(jLabelLiveEditing, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelPermissionsTopLayout.setVerticalGroup(
            jPanelPermissionsTopLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelPermissionsTopLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabelLiveEditing)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanelPermissionsBottom.setBackground(new java.awt.Color(255, 255, 255));

        jLabelRecordInfo.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabelRecordInfo.setText("<html><div style=\"width:100%\"><center><p>Recording how often and where SIMKit is used is important in ensuring that this software remains free for all to use</p></center></div></html>");

        jLabelCollectAnonymous.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabelCollectAnonymous.setText("<html><div style=\"width:100%\"><p>Allow SIMKit to collect anonymous data about the way you use this app (not including the messages you write)</p></div></html>");

        jLabelCollectUsage.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabelCollectUsage.setText("<html><div style=\"width:100%\"><p>Allow SIMKit to register that this app was turned on (collecting this very basic usage data helps us keep SIMKit free, please keep this in mind before unchecking this option)</p></div></html>");

        jToggleButtonUsage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensimkit/resources/YesNoNo.png"))); // NOI18N
        jToggleButtonUsage.setBorderPainted(false);
        jToggleButtonUsage.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensimkit/resources/YesNoYes.png"))); // NOI18N
        jToggleButtonUsage.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButtonUsageItemStateChanged(evt);
            }
        });

        jToggleButtonTurnedOn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensimkit/resources/YesNoNo.png"))); // NOI18N
        jToggleButtonTurnedOn.setBorderPainted(false);
        jToggleButtonTurnedOn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensimkit/resources/YesNoYes.png"))); // NOI18N
        jToggleButtonTurnedOn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButtonTurnedOnItemStateChanged(evt);
            }
        });

        jButtonContinue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/opensimkit/resources/ContinueButton.png"))); // NOI18N
        jButtonContinue.setBorderPainted(false);
        jButtonContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinueActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelPermissionsBottomLayout = new org.jdesktop.layout.GroupLayout(jPanelPermissionsBottom);
        jPanelPermissionsBottom.setLayout(jPanelPermissionsBottomLayout);
        jPanelPermissionsBottomLayout.setHorizontalGroup(
            jPanelPermissionsBottomLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelPermissionsBottomLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanelPermissionsBottomLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelPermissionsBottomLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(jLabelRecordInfo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .add(jPanelPermissionsBottomLayout.createSequentialGroup()
                            .add(jPanelPermissionsBottomLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(jLabelCollectAnonymous, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                                .add(jLabelCollectUsage, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(jPanelPermissionsBottomLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(jToggleButtonUsage)
                                .add(jToggleButtonTurnedOn))
                            .add(5, 5, 5)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelPermissionsBottomLayout.createSequentialGroup()
                        .add(jButtonContinue)
                        .addContainerGap())))
        );
        jPanelPermissionsBottomLayout.setVerticalGroup(
            jPanelPermissionsBottomLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelPermissionsBottomLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabelRecordInfo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(44, 44, 44)
                .add(jPanelPermissionsBottomLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabelCollectAnonymous, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jToggleButtonUsage))
                .add(31, 31, 31)
                .add(jPanelPermissionsBottomLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabelCollectUsage, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jToggleButtonTurnedOn))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButtonContinue))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanelPermissionsBottom, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanelPermissionsTop, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelPermissionsTop, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelPermissionsBottom, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinueActionPerformed
        // TODO add your handling code here:
        OpenSIMKit.anonymousDataCollection.saveXMLSettings(usageYes, turnedOnYes);
        OpenSIMKit.mainFrame.setDisconnectedInterface();
    }//GEN-LAST:event_jButtonContinueActionPerformed

    private void jToggleButtonUsageItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jToggleButtonUsageItemStateChanged
        // TODO add your handling code here:
        usageYes = (evt.getStateChange() == evt.SELECTED);
        
        if(usageYes)
        {
            jToggleButtonUsage.setIcon(yesNoYesIcon);
        }
        else
        {
            jToggleButtonUsage.setIcon(yesNoNoIcon);
        }
    }//GEN-LAST:event_jToggleButtonUsageItemStateChanged

    private void jToggleButtonTurnedOnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jToggleButtonTurnedOnItemStateChanged
        // TODO add your handling code here:
        turnedOnYes = (evt.getStateChange() == evt.SELECTED);
        
        if(turnedOnYes)
        {
            jToggleButtonTurnedOn.setIcon(yesNoYesIcon);
        }
        else
        {
            jToggleButtonTurnedOn.setIcon(yesNoNoIcon);
        }
    }//GEN-LAST:event_jToggleButtonTurnedOnItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonContinue;
    private javax.swing.JLabel jLabelCollectAnonymous;
    private javax.swing.JLabel jLabelCollectUsage;
    private javax.swing.JLabel jLabelLiveEditing;
    private javax.swing.JLabel jLabelRecordInfo;
    private javax.swing.JPanel jPanelPermissionsBottom;
    private javax.swing.JPanel jPanelPermissionsTop;
    private javax.swing.JToggleButton jToggleButtonTurnedOn;
    private javax.swing.JToggleButton jToggleButtonUsage;
    // End of variables declaration//GEN-END:variables
}
